title: Alex Allain
author:
  name: Alex Allain
  email: alex.allain@gmail.com
description: >-
  Personal site and writing by Alex Allain.
url: https://alexallain.github.io
baseurl: ""

permalink: /writing/:title/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - node_modules
